### ISSUE TITLE
Fireball Epic

### ISSUE THREAD

**Issue by amirobinsonmuto** [chingu-voyages/v45-tier2-team-23#17]
**__Feature Description__**
This app will help anyone interested in these events explore this data in novel ways. It will summarize this data and will allow users to select subsets of it for more detailed analysis.

**__Major User Stories/tasks__**
- [ ] As a user, I want to access a comprehensive list of meteorite strikes from the NASA API.
- [ ] As a user, I want to view a heatmap showcasing all meteorite strikes, either displaying all strikes or a chosen subset.
- [ ] As a user, I want the ability to filter meteorite strikes based on various criteria like age, mass, name, date range, and mass range.
- [ ] As a user, I want to view informative summary metrics for the selected data or for the entire dataset if no specific search criteria are applied.

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
